nelmio_cors:
    paths:
        '^/api':
            origin_regex: false
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600
            forced_allow_origin_value: '*'
