<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630022008 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table reservation — réservations B2C invité (isolées par centre, FK prestation même centre).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creneau TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nb_personnes INT NOT NULL, nom_invite VARCHAR(120) NOT NULL, email_invite VARCHAR(180) NOT NULL, telephone_invite VARCHAR(30) NOT NULL, montant_total_cents INT NOT NULL, acompte_cents INT NOT NULL, statut VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, centre_id INT NOT NULL, prestation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42C849559E45C554 ON reservation (prestation_id)');
        $this->addSql('CREATE INDEX idx_reservation_centre ON reservation (centre_id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849559E45C554 FOREIGN KEY (prestation_id) REFERENCES prestation (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955463CD7C3');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C849559E45C554');
        $this->addSql('DROP TABLE reservation');
    }
}
