<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701010215 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Core IA : ia_quota (compteur mensuel par centre) + ia_usage (journal des consos).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ia_quota (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, periode VARCHAR(7) NOT NULL, appels INT DEFAULT 0 NOT NULL, centre_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D0A1617A463CD7C3 ON ia_quota (centre_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ia_quota_centre_periode ON ia_quota (centre_id, periode)');
        $this->addSql('CREATE TABLE ia_usage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usage_type VARCHAR(60) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, centre_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ia_usage_centre ON ia_usage (centre_id)');
        $this->addSql('ALTER TABLE ia_quota ADD CONSTRAINT FK_D0A1617A463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ia_usage ADD CONSTRAINT FK_6C5630E7463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ia_quota DROP CONSTRAINT FK_D0A1617A463CD7C3');
        $this->addSql('ALTER TABLE ia_usage DROP CONSTRAINT FK_6C5630E7463CD7C3');
        $this->addSql('DROP TABLE ia_quota');
        $this->addSql('DROP TABLE ia_usage');
    }
}
