<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611000612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE absence (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              date DATE NOT NULL,
              type VARCHAR(30) NOT NULL,
              motif VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              user_id INT NOT NULL,
              created_by INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_765AE0C9463CD7C3 ON absence (centre_id)');
        $this->addSql('CREATE INDEX IDX_765AE0C9A76ED395 ON absence (user_id)');
        $this->addSql('CREATE INDEX IDX_765AE0C9DE12AB56 ON absence (created_by)');
        $this->addSql('CREATE UNIQUE INDEX uniq_absence_user_date ON absence (user_id, date)');
        $this->addSql(<<<'SQL'
            CREATE TABLE audit_log (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              action VARCHAR(100) NOT NULL,
              target_type VARCHAR(50) NOT NULL,
              target_id INT DEFAULT NULL,
              metadata JSON DEFAULT NULL,
              ip VARCHAR(45) DEFAULT NULL,
              user_agent VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              super_admin_user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_F6E1C0F5B8CD8675 ON audit_log (super_admin_user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE centre (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(100) NOT NULL,
              slug VARCHAR(120) NOT NULL,
              adresse VARCHAR(255) DEFAULT NULL,
              telephone VARCHAR(30) DEFAULT NULL,
              site_web VARCHAR(255) DEFAULT NULL,
              opening_hours JSON DEFAULT NULL,
              tenue_haut VARCHAR(120) DEFAULT NULL,
              tenue_bas VARCHAR(120) DEFAULT NULL,
              tenue_chaussures VARCHAR(120) DEFAULT NULL,
              actif BOOLEAN DEFAULT true NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C6A0EA75989D9B62 ON centre (slug)');
        $this->addSql(<<<'SQL'
            CREATE TABLE centre_note (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              contenu TEXT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              super_admin_user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_5EB06944463CD7C3 ON centre_note (centre_id)');
        $this->addSql('CREATE INDEX IDX_5EB06944B8CD8675 ON centre_note (super_admin_user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE competence (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(150) NOT NULL,
              points INT NOT NULL,
              difficulte VARCHAR(30) NOT NULL,
              description TEXT DEFAULT NULL,
              zone_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_94D4687F9F2C3FAB ON competence (zone_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE completion (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              completed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              photo_path VARCHAR(255) DEFAULT NULL,
              photo_mime_type VARCHAR(50) DEFAULT NULL,
              photo_taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              poste_id INT NOT NULL,
              mission_id INT NOT NULL,
              user_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_38D6377EA0905086 ON completion (poste_id)');
        $this->addSql('CREATE INDEX IDX_38D6377EBE6CAE90 ON completion (mission_id)');
        $this->addSql('CREATE INDEX IDX_38D6377EA76ED395 ON completion (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_completion ON completion (poste_id, mission_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE completion_haccp_proof (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              valeur_numerique NUMERIC(5, 2) DEFAULT NULL,
              date_releve DATE DEFAULT NULL,
              photo_path VARCHAR(255) DEFAULT NULL,
              photo_mime_type VARCHAR(50) DEFAULT NULL,
              note TEXT DEFAULT NULL,
              est_conforme BOOLEAN DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              completion_id INT NOT NULL,
              centre_id INT NOT NULL,
              releve_par_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_FD254D60463CD7C3 ON completion_haccp_proof (centre_id)');
        $this->addSql('CREATE INDEX idx_haccp_proof_centre_date ON completion_haccp_proof (centre_id, created_at)');
        $this->addSql('CREATE INDEX idx_haccp_proof_releveur ON completion_haccp_proof (releve_par_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_haccp_proof_completion ON completion_haccp_proof (completion_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE correction_pointage (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              champ_modifie VARCHAR(50) NOT NULL,
              ancienne_valeur TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              nouvelle_valeur TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              motif TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              pointage_id INT NOT NULL,
              pause_id INT DEFAULT NULL,
              corrige_par_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_66097CCEE58DA11D ON correction_pointage (pointage_id)');
        $this->addSql('CREATE INDEX IDX_66097CCE94D614D6 ON correction_pointage (pause_id)');
        $this->addSql('CREATE INDEX IDX_66097CCEC99BFB58 ON correction_pointage (corrige_par_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE event_log (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              entity_type VARCHAR(50) NOT NULL,
              entity_id INT DEFAULT NULL,
              action VARCHAR(20) NOT NULL,
              payload JSON NOT NULL,
              occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              user_id INT DEFAULT NULL,
              poste_id INT DEFAULT NULL,
              mission_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_9EF0AD16463CD7C3 ON event_log (centre_id)');
        $this->addSql('CREATE INDEX idx_eventlog_centre_type_date ON event_log (centre_id, entity_type, occurred_at)');
        $this->addSql('CREATE INDEX idx_eventlog_centre_user_date ON event_log (centre_id, user_id, occurred_at)');
        $this->addSql('CREATE INDEX idx_eventlog_poste ON event_log (poste_id)');
        $this->addSql('CREATE INDEX idx_eventlog_mission ON event_log (mission_id)');
        $this->addSql('CREATE INDEX idx_eventlog_user ON event_log (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE haccp_equipement (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(120) NOT NULL,
              type VARCHAR(20) NOT NULL,
              seuil_min NUMERIC(5, 2) NOT NULL,
              seuil_max NUMERIC(5, 2) NOT NULL,
              unite VARCHAR(10) DEFAULT '°C' NOT NULL,
              ordre INT DEFAULT 0 NOT NULL,
              actif BOOLEAN DEFAULT true NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              zone_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_8A9BDD67463CD7C3 ON haccp_equipement (centre_id)');
        $this->addSql('CREATE INDEX idx_haccp_equip_centre ON haccp_equipement (centre_id, actif)');
        $this->addSql('CREATE INDEX idx_haccp_equip_zone ON haccp_equipement (zone_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE incident (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              titre VARCHAR(255) NOT NULL,
              severite VARCHAR(20) NOT NULL,
              statut VARCHAR(20) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              centre_id INT NOT NULL,
              service_id INT DEFAULT NULL,
              user_id INT DEFAULT NULL,
              zone_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_3D03A11A463CD7C3 ON incident (centre_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11AED5CA9E6 ON incident (service_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11AA76ED395 ON incident (user_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11A9F2C3FAB ON incident (zone_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE incident_staff (
              incident_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (incident_id, user_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_195A51F859E53FB9 ON incident_staff (incident_id)');
        $this->addSql('CREATE INDEX IDX_195A51F8A76ED395 ON incident_staff (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE "lead" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              intent VARCHAR(20) NOT NULL,
              plan VARCHAR(20) NOT NULL,
              name VARCHAR(120) NOT NULL,
              email VARCHAR(180) NOT NULL,
              phone VARCHAR(30) NOT NULL,
              centre VARCHAR(180) NOT NULL,
              activity VARCHAR(30) NOT NULL,
              staff_size VARCHAR(20) NOT NULL,
              city VARCHAR(120) DEFAULT NULL,
              zip VARCHAR(10) DEFAULT NULL,
              preferred_slot TEXT DEFAULT NULL,
              channel VARCHAR(20) DEFAULT NULL,
              custom_needs TEXT DEFAULT NULL,
              message TEXT DEFAULT NULL,
              consent BOOLEAN NOT NULL,
              consent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              source VARCHAR(80) NOT NULL,
              status VARCHAR(20) NOT NULL,
              notes TEXT DEFAULT NULL,
              handled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              handled_by_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_289161CBFE65AF40 ON "lead" (handled_by_id)');
        $this->addSql('CREATE INDEX idx_lead_status ON "lead" (status)');
        $this->addSql('CREATE INDEX idx_lead_created_at ON "lead" (created_at)');
        $this->addSql('CREATE INDEX idx_lead_intent ON "lead" (intent)');
        $this->addSql(<<<'SQL'
            CREATE TABLE media (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              entity_type VARCHAR(20) NOT NULL,
              entity_id INT NOT NULL,
              filename VARCHAR(255) NOT NULL,
              mime_type VARCHAR(100) NOT NULL,
              size_bytes INT NOT NULL,
              storage_path VARCHAR(500) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              uploaded_by_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6A2CA10C463CD7C3 ON media (centre_id)');
        $this->addSql('CREATE INDEX IDX_6A2CA10CA2B28FE8 ON media (uploaded_by_id)');
        $this->addSql('CREATE INDEX idx_media_entity ON media (entity_type, entity_id, centre_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE mission (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              texte VARCHAR(255) NOT NULL,
              categorie VARCHAR(30) NOT NULL,
              frequence VARCHAR(20) NOT NULL,
              priorite VARCHAR(30) NOT NULL,
              ordre INT NOT NULL,
              requires_photo BOOLEAN DEFAULT false NOT NULL,
              zone_id INT NOT NULL,
              service_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_9067F23C9F2C3FAB ON mission (zone_id)');
        $this->addSql('CREATE INDEX IDX_9067F23CED5CA9E6 ON mission (service_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE mission_categorie (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(50) NOT NULL,
              couleur VARCHAR(20) NOT NULL,
              icone VARCHAR(32) DEFAULT NULL,
              ordre INT NOT NULL,
              centre_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_FBC8211D463CD7C3 ON mission_categorie (centre_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_mission_cat_centre_nom ON mission_categorie (centre_id, nom)');
        $this->addSql(<<<'SQL'
            CREATE TABLE mission_haccp_spec (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type_releve VARCHAR(20) NOT NULL,
              moment VARCHAR(20) DEFAULT NULL,
              seuil_min NUMERIC(5, 2) DEFAULT NULL,
              seuil_max NUMERIC(5, 2) DEFAULT NULL,
              unite VARCHAR(10) DEFAULT NULL,
              photo_obligatoire BOOLEAN DEFAULT false NOT NULL,
              commentaire_obligatoire BOOLEAN DEFAULT false NOT NULL,
              archivee BOOLEAN DEFAULT false NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              mission_id INT NOT NULL,
              centre_id INT NOT NULL,
              equipement_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_haccp_spec_centre ON mission_haccp_spec (centre_id)');
        $this->addSql('CREATE INDEX idx_haccp_spec_equipement ON mission_haccp_spec (equipement_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_haccp_spec_mission ON mission_haccp_spec (mission_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_snapshot (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              week_start DATE NOT NULL,
              published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              data JSON NOT NULL,
              motif_modification TEXT DEFAULT NULL,
              checksum VARCHAR(64) NOT NULL,
              delai_respect BOOLEAN NOT NULL,
              centre_id INT NOT NULL,
              published_by INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_1B484398463CD7C3 ON planning_snapshot (centre_id)');
        $this->addSql('CREATE INDEX IDX_1B484398B548D29F ON planning_snapshot (published_by)');
        $this->addSql('CREATE INDEX idx_ps_centre_week ON planning_snapshot (centre_id, week_start)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_template (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(100) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              created_by_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_A065492E463CD7C3 ON planning_template (centre_id)');
        $this->addSql('CREATE INDEX IDX_A065492EB03A8386 ON planning_template (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_planning_template_centre_nom ON planning_template (centre_id, nom)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_template_absence (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              day_of_week SMALLINT NOT NULL,
              type VARCHAR(30) NOT NULL,
              motif VARCHAR(255) DEFAULT NULL,
              template_id INT NOT NULL,
              user_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_176340055DA0FB8 ON planning_template_absence (template_id)');
        $this->addSql('CREATE INDEX IDX_17634005A76ED395 ON planning_template_absence (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_template_shift (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              day_of_week SMALLINT NOT NULL,
              heure_debut TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              heure_fin TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              pause_minutes INT DEFAULT 0 NOT NULL,
              note VARCHAR(500) DEFAULT NULL,
              template_id INT NOT NULL,
              zone_id INT NOT NULL,
              user_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_92F6D3F65DA0FB8 ON planning_template_shift (template_id)');
        $this->addSql('CREATE INDEX IDX_92F6D3F69F2C3FAB ON planning_template_shift (zone_id)');
        $this->addSql('CREATE INDEX IDX_92F6D3F6A76ED395 ON planning_template_shift (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_week (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              week_start DATE NOT NULL,
              statut VARCHAR(20) NOT NULL,
              published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              note TEXT DEFAULT NULL,
              last_modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              centre_id INT NOT NULL,
              published_by_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_938C618E463CD7C3 ON planning_week (centre_id)');
        $this->addSql('CREATE INDEX IDX_938C618E5B075477 ON planning_week (published_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pw_centre_week ON planning_week (centre_id, week_start)');
        $this->addSql(<<<'SQL'
            CREATE TABLE pointage (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              heure_arrivee TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              heure_depart TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              statut VARCHAR(20) NOT NULL,
              commentaire TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              centre_id INT NOT NULL,
              service_id INT NOT NULL,
              poste_id INT DEFAULT NULL,
              user_id INT NOT NULL,
              pointe_par_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7591B20463CD7C3 ON pointage (centre_id)');
        $this->addSql('CREATE INDEX IDX_7591B20ED5CA9E6 ON pointage (service_id)');
        $this->addSql('CREATE INDEX IDX_7591B20A0905086 ON pointage (poste_id)');
        $this->addSql('CREATE INDEX IDX_7591B20A76ED395 ON pointage (user_id)');
        $this->addSql('CREATE INDEX IDX_7591B201C6ED750 ON pointage (pointe_par_id)');
        $this->addSql('CREATE INDEX idx_pointage_centre_service ON pointage (centre_id, service_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE pointage_pause (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              heure_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              heure_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              type VARCHAR(20) NOT NULL,
              pointage_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_FE748B79E58DA11D ON pointage_pause (pointage_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE poste (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              heure_debut TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              heure_fin TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              pause_minutes INT DEFAULT 0 NOT NULL,
              note VARCHAR(500) DEFAULT NULL,
              service_id INT NOT NULL,
              zone_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7C890FABED5CA9E6 ON poste (service_id)');
        $this->addSql('CREATE INDEX IDX_7C890FAB9F2C3FAB ON poste (zone_id)');
        $this->addSql('CREATE INDEX IDX_7C890FABA76ED395 ON poste (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_poste ON poste (service_id, zone_id, user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE service (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              date DATE NOT NULL,
              heure_debut TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              heure_fin TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
              statut VARCHAR(20) NOT NULL,
              taux_completion DOUBLE PRECISION DEFAULT 0 NOT NULL,
              note TEXT DEFAULT NULL,
              missions_snapshot JSON DEFAULT NULL,
              centre_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_E19D9AD2463CD7C3 ON service (centre_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_service_centre_date ON service (centre_id, date)');
        $this->addSql(<<<'SQL'
            CREATE TABLE service_manager (
              service_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (service_id, user_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_35A07725ED5CA9E6 ON service_manager (service_id)');
        $this->addSql('CREATE INDEX IDX_35A07725A76ED395 ON service_manager (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE staff_competence (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              competence_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_728678AEA76ED395 ON staff_competence (user_id)');
        $this->addSql('CREATE INDEX IDX_728678AE15761DAB ON staff_competence (competence_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_staff_comp ON staff_competence (user_id, competence_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE support_attachment (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              filename VARCHAR(255) NOT NULL,
              stored_path VARCHAR(500) NOT NULL,
              mime_type VARCHAR(100) NOT NULL,
              size INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              ticket_id INT DEFAULT NULL,
              reply_id INT DEFAULT NULL,
              uploaded_by_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_5BEB1D99700047D2 ON support_attachment (ticket_id)');
        $this->addSql('CREATE INDEX IDX_5BEB1D998A0E4E7F ON support_attachment (reply_id)');
        $this->addSql('CREATE INDEX IDX_5BEB1D99A2B28FE8 ON support_attachment (uploaded_by_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE support_reply (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              message TEXT NOT NULL,
              interne BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              ticket_id INT NOT NULL,
              auteur_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_F12D038700047D2 ON support_reply (ticket_id)');
        $this->addSql('CREATE INDEX IDX_F12D03860BB6FE6 ON support_reply (auteur_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE support_ticket (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              sujet VARCHAR(200) NOT NULL,
              message TEXT NOT NULL,
              categorie VARCHAR(30) NOT NULL,
              statut VARCHAR(20) NOT NULL,
              priorite VARCHAR(20) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              last_viewed_by_super_admin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              last_viewed_by_author TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              centre_id INT NOT NULL,
              auteur_id INT NOT NULL,
              assigne_a_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_1F5A4D53463CD7C3 ON support_ticket (centre_id)');
        $this->addSql('CREATE INDEX IDX_1F5A4D5360BB6FE6 ON support_ticket (auteur_id)');
        $this->addSql('CREATE INDEX IDX_1F5A4D53BB1B0F33 ON support_ticket (assigne_a_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE tuto_read (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              tutoriel_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_4D239655A76ED395 ON tuto_read (user_id)');
        $this->addSql('CREATE INDEX IDX_4D2396557CB6CDBB ON tuto_read (tutoriel_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tutoread ON tuto_read (user_id, tutoriel_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE tutoriel (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              titre VARCHAR(200) NOT NULL,
              niveau VARCHAR(20) NOT NULL,
              dure_min INT DEFAULT NULL,
              contenu JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              zone_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_A2073AED463CD7C3 ON tutoriel (centre_id)');
        $this->addSql('CREATE INDEX IDX_A2073AED9F2C3FAB ON tutoriel (zone_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(100) NOT NULL,
              email VARCHAR(180) NOT NULL,
              password VARCHAR(255) NOT NULL,
              roles JSON NOT NULL,
              role VARCHAR(20) NOT NULL,
              avatar_color VARCHAR(20) DEFAULT NULL,
              points INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              prenom VARCHAR(100) DEFAULT NULL,
              taille_haut VARCHAR(255) DEFAULT NULL,
              taille_bas VARCHAR(255) DEFAULT NULL,
              pointure VARCHAR(10) DEFAULT NULL,
              actif BOOLEAN DEFAULT true NOT NULL,
              heures_hebdo INT DEFAULT NULL,
              type_contrat VARCHAR(30) DEFAULT NULL,
              code_pointage VARCHAR(4) DEFAULT NULL,
              date_embauche DATE DEFAULT NULL,
              date_naissance DATE DEFAULT NULL,
              lieu_naissance_commune VARCHAR(120) DEFAULT NULL,
              lieu_naissance_departement VARCHAR(60) DEFAULT NULL,
              sexe VARCHAR(1) DEFAULT NULL,
              nationalite VARCHAR(60) DEFAULT NULL,
              emploi VARCHAR(120) DEFAULT NULL,
              adresse VARCHAR(255) DEFAULT NULL,
              code_postal VARCHAR(10) DEFAULT NULL,
              ville VARCHAR(120) DEFAULT NULL,
              telephone VARCHAR(20) DEFAULT NULL,
              date_sortie DATE DEFAULT NULL,
              motif_sortie VARCHAR(40) DEFAULT NULL,
              centre_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D649463CD7C3 ON "user" (centre_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE validation_hebdo (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              semaine DATE NOT NULL,
              statut VARCHAR(20) NOT NULL,
              heures_travaillees INT NOT NULL,
              heures_prevues INT NOT NULL,
              ecart INT NOT NULL,
              heures_sup INT NOT NULL,
              nb_retards INT NOT NULL,
              nb_absences INT NOT NULL,
              commentaire TEXT DEFAULT NULL,
              valide_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              centre_id INT NOT NULL,
              user_id INT NOT NULL,
              valide_par_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_1C440497463CD7C3 ON validation_hebdo (centre_id)');
        $this->addSql('CREATE INDEX IDX_1C440497A76ED395 ON validation_hebdo (user_id)');
        $this->addSql('CREATE INDEX IDX_1C4404976AF12ED9 ON validation_hebdo (valide_par_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_validation_centre_user_semaine ON validation_hebdo (centre_id, user_id, semaine)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE zone (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(50) NOT NULL,
              couleur VARCHAR(20) DEFAULT NULL,
              ordre INT NOT NULL,
              centre_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_A0EBC007463CD7C3 ON zone (centre_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_zone_centre_nom ON zone (centre_id, nom)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              absence
            ADD
              CONSTRAINT FK_765AE0C9463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              absence
            ADD
              CONSTRAINT FK_765AE0C9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              absence
            ADD
              CONSTRAINT FK_765AE0C9DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              audit_log
            ADD
              CONSTRAINT FK_F6E1C0F5B8CD8675 FOREIGN KEY (super_admin_user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              centre_note
            ADD
              CONSTRAINT FK_5EB06944463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              centre_note
            ADD
              CONSTRAINT FK_5EB06944B8CD8675 FOREIGN KEY (super_admin_user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              competence
            ADD
              CONSTRAINT FK_94D4687F9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              completion
            ADD
              CONSTRAINT FK_38D6377EA0905086 FOREIGN KEY (poste_id) REFERENCES poste (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              completion
            ADD
              CONSTRAINT FK_38D6377EBE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              completion
            ADD
              CONSTRAINT FK_38D6377EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              completion_haccp_proof
            ADD
              CONSTRAINT FK_FD254D60C7995787 FOREIGN KEY (completion_id) REFERENCES completion (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              completion_haccp_proof
            ADD
              CONSTRAINT FK_FD254D60463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              completion_haccp_proof
            ADD
              CONSTRAINT FK_FD254D603144F549 FOREIGN KEY (releve_par_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              correction_pointage
            ADD
              CONSTRAINT FK_66097CCEE58DA11D FOREIGN KEY (pointage_id) REFERENCES pointage (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              correction_pointage
            ADD
              CONSTRAINT FK_66097CCE94D614D6 FOREIGN KEY (pause_id) REFERENCES pointage_pause (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              correction_pointage
            ADD
              CONSTRAINT FK_66097CCEC99BFB58 FOREIGN KEY (corrige_par_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              event_log
            ADD
              CONSTRAINT FK_9EF0AD16463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              event_log
            ADD
              CONSTRAINT FK_9EF0AD16A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              event_log
            ADD
              CONSTRAINT FK_9EF0AD16A0905086 FOREIGN KEY (poste_id) REFERENCES poste (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              event_log
            ADD
              CONSTRAINT FK_9EF0AD16BE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              haccp_equipement
            ADD
              CONSTRAINT FK_8A9BDD67463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              haccp_equipement
            ADD
              CONSTRAINT FK_8A9BDD679F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              incident
            ADD
              CONSTRAINT FK_3D03A11A463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              incident
            ADD
              CONSTRAINT FK_3D03A11AED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              incident
            ADD
              CONSTRAINT FK_3D03A11AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              incident
            ADD
              CONSTRAINT FK_3D03A11A9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              incident_staff
            ADD
              CONSTRAINT FK_195A51F859E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              incident_staff
            ADD
              CONSTRAINT FK_195A51F8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              "lead"
            ADD
              CONSTRAINT FK_289161CBFE65AF40 FOREIGN KEY (handled_by_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              media
            ADD
              CONSTRAINT FK_6A2CA10C463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              media
            ADD
              CONSTRAINT FK_6A2CA10CA2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              mission
            ADD
              CONSTRAINT FK_9067F23C9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              mission
            ADD
              CONSTRAINT FK_9067F23CED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              mission_categorie
            ADD
              CONSTRAINT FK_FBC8211D463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              mission_haccp_spec
            ADD
              CONSTRAINT FK_9CB3F857BE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              mission_haccp_spec
            ADD
              CONSTRAINT FK_9CB3F857463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              mission_haccp_spec
            ADD
              CONSTRAINT FK_9CB3F857806F0F5C FOREIGN KEY (equipement_id) REFERENCES haccp_equipement (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_snapshot
            ADD
              CONSTRAINT FK_1B484398463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_snapshot
            ADD
              CONSTRAINT FK_1B484398B548D29F FOREIGN KEY (published_by) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_template
            ADD
              CONSTRAINT FK_A065492E463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_template
            ADD
              CONSTRAINT FK_A065492EB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_template_absence
            ADD
              CONSTRAINT FK_176340055DA0FB8 FOREIGN KEY (template_id) REFERENCES planning_template (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_template_absence
            ADD
              CONSTRAINT FK_17634005A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_template_shift
            ADD
              CONSTRAINT FK_92F6D3F65DA0FB8 FOREIGN KEY (template_id) REFERENCES planning_template (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_template_shift
            ADD
              CONSTRAINT FK_92F6D3F69F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_template_shift
            ADD
              CONSTRAINT FK_92F6D3F6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_week
            ADD
              CONSTRAINT FK_938C618E463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_week
            ADD
              CONSTRAINT FK_938C618E5B075477 FOREIGN KEY (published_by_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pointage
            ADD
              CONSTRAINT FK_7591B20463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pointage
            ADD
              CONSTRAINT FK_7591B20ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pointage
            ADD
              CONSTRAINT FK_7591B20A0905086 FOREIGN KEY (poste_id) REFERENCES poste (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pointage
            ADD
              CONSTRAINT FK_7591B20A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pointage
            ADD
              CONSTRAINT FK_7591B201C6ED750 FOREIGN KEY (pointe_par_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pointage_pause
            ADD
              CONSTRAINT FK_FE748B79E58DA11D FOREIGN KEY (pointage_id) REFERENCES pointage (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              poste
            ADD
              CONSTRAINT FK_7C890FABED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              poste
            ADD
              CONSTRAINT FK_7C890FAB9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              poste
            ADD
              CONSTRAINT FK_7C890FABA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              service
            ADD
              CONSTRAINT FK_E19D9AD2463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              service_manager
            ADD
              CONSTRAINT FK_35A07725ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              service_manager
            ADD
              CONSTRAINT FK_35A07725A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              staff_competence
            ADD
              CONSTRAINT FK_728678AEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              staff_competence
            ADD
              CONSTRAINT FK_728678AE15761DAB FOREIGN KEY (competence_id) REFERENCES competence (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_attachment
            ADD
              CONSTRAINT FK_5BEB1D99700047D2 FOREIGN KEY (ticket_id) REFERENCES support_ticket (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_attachment
            ADD
              CONSTRAINT FK_5BEB1D998A0E4E7F FOREIGN KEY (reply_id) REFERENCES support_reply (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_attachment
            ADD
              CONSTRAINT FK_5BEB1D99A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_reply
            ADD
              CONSTRAINT FK_F12D038700047D2 FOREIGN KEY (ticket_id) REFERENCES support_ticket (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_reply
            ADD
              CONSTRAINT FK_F12D03860BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_ticket
            ADD
              CONSTRAINT FK_1F5A4D53463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_ticket
            ADD
              CONSTRAINT FK_1F5A4D5360BB6FE6 FOREIGN KEY (auteur_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              support_ticket
            ADD
              CONSTRAINT FK_1F5A4D53BB1B0F33 FOREIGN KEY (assigne_a_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tuto_read
            ADD
              CONSTRAINT FK_4D239655A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tuto_read
            ADD
              CONSTRAINT FK_4D2396557CB6CDBB FOREIGN KEY (tutoriel_id) REFERENCES tutoriel (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tutoriel
            ADD
              CONSTRAINT FK_A2073AED463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tutoriel
            ADD
              CONSTRAINT FK_A2073AED9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              "user"
            ADD
              CONSTRAINT FK_8D93D649463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              validation_hebdo
            ADD
              CONSTRAINT FK_1C440497463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              validation_hebdo
            ADD
              CONSTRAINT FK_1C440497A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              validation_hebdo
            ADD
              CONSTRAINT FK_1C4404976AF12ED9 FOREIGN KEY (valide_par_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              zone
            ADD
              CONSTRAINT FK_A0EBC007463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE absence DROP CONSTRAINT FK_765AE0C9463CD7C3');
        $this->addSql('ALTER TABLE absence DROP CONSTRAINT FK_765AE0C9A76ED395');
        $this->addSql('ALTER TABLE absence DROP CONSTRAINT FK_765AE0C9DE12AB56');
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F5B8CD8675');
        $this->addSql('ALTER TABLE centre_note DROP CONSTRAINT FK_5EB06944463CD7C3');
        $this->addSql('ALTER TABLE centre_note DROP CONSTRAINT FK_5EB06944B8CD8675');
        $this->addSql('ALTER TABLE competence DROP CONSTRAINT FK_94D4687F9F2C3FAB');
        $this->addSql('ALTER TABLE completion DROP CONSTRAINT FK_38D6377EA0905086');
        $this->addSql('ALTER TABLE completion DROP CONSTRAINT FK_38D6377EBE6CAE90');
        $this->addSql('ALTER TABLE completion DROP CONSTRAINT FK_38D6377EA76ED395');
        $this->addSql('ALTER TABLE completion_haccp_proof DROP CONSTRAINT FK_FD254D60C7995787');
        $this->addSql('ALTER TABLE completion_haccp_proof DROP CONSTRAINT FK_FD254D60463CD7C3');
        $this->addSql('ALTER TABLE completion_haccp_proof DROP CONSTRAINT FK_FD254D603144F549');
        $this->addSql('ALTER TABLE correction_pointage DROP CONSTRAINT FK_66097CCEE58DA11D');
        $this->addSql('ALTER TABLE correction_pointage DROP CONSTRAINT FK_66097CCE94D614D6');
        $this->addSql('ALTER TABLE correction_pointage DROP CONSTRAINT FK_66097CCEC99BFB58');
        $this->addSql('ALTER TABLE event_log DROP CONSTRAINT FK_9EF0AD16463CD7C3');
        $this->addSql('ALTER TABLE event_log DROP CONSTRAINT FK_9EF0AD16A76ED395');
        $this->addSql('ALTER TABLE event_log DROP CONSTRAINT FK_9EF0AD16A0905086');
        $this->addSql('ALTER TABLE event_log DROP CONSTRAINT FK_9EF0AD16BE6CAE90');
        $this->addSql('ALTER TABLE haccp_equipement DROP CONSTRAINT FK_8A9BDD67463CD7C3');
        $this->addSql('ALTER TABLE haccp_equipement DROP CONSTRAINT FK_8A9BDD679F2C3FAB');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11A463CD7C3');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11AED5CA9E6');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11AA76ED395');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11A9F2C3FAB');
        $this->addSql('ALTER TABLE incident_staff DROP CONSTRAINT FK_195A51F859E53FB9');
        $this->addSql('ALTER TABLE incident_staff DROP CONSTRAINT FK_195A51F8A76ED395');
        $this->addSql('ALTER TABLE "lead" DROP CONSTRAINT FK_289161CBFE65AF40');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C463CD7C3');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CA2B28FE8');
        $this->addSql('ALTER TABLE mission DROP CONSTRAINT FK_9067F23C9F2C3FAB');
        $this->addSql('ALTER TABLE mission DROP CONSTRAINT FK_9067F23CED5CA9E6');
        $this->addSql('ALTER TABLE mission_categorie DROP CONSTRAINT FK_FBC8211D463CD7C3');
        $this->addSql('ALTER TABLE mission_haccp_spec DROP CONSTRAINT FK_9CB3F857BE6CAE90');
        $this->addSql('ALTER TABLE mission_haccp_spec DROP CONSTRAINT FK_9CB3F857463CD7C3');
        $this->addSql('ALTER TABLE mission_haccp_spec DROP CONSTRAINT FK_9CB3F857806F0F5C');
        $this->addSql('ALTER TABLE planning_snapshot DROP CONSTRAINT FK_1B484398463CD7C3');
        $this->addSql('ALTER TABLE planning_snapshot DROP CONSTRAINT FK_1B484398B548D29F');
        $this->addSql('ALTER TABLE planning_template DROP CONSTRAINT FK_A065492E463CD7C3');
        $this->addSql('ALTER TABLE planning_template DROP CONSTRAINT FK_A065492EB03A8386');
        $this->addSql('ALTER TABLE planning_template_absence DROP CONSTRAINT FK_176340055DA0FB8');
        $this->addSql('ALTER TABLE planning_template_absence DROP CONSTRAINT FK_17634005A76ED395');
        $this->addSql('ALTER TABLE planning_template_shift DROP CONSTRAINT FK_92F6D3F65DA0FB8');
        $this->addSql('ALTER TABLE planning_template_shift DROP CONSTRAINT FK_92F6D3F69F2C3FAB');
        $this->addSql('ALTER TABLE planning_template_shift DROP CONSTRAINT FK_92F6D3F6A76ED395');
        $this->addSql('ALTER TABLE planning_week DROP CONSTRAINT FK_938C618E463CD7C3');
        $this->addSql('ALTER TABLE planning_week DROP CONSTRAINT FK_938C618E5B075477');
        $this->addSql('ALTER TABLE pointage DROP CONSTRAINT FK_7591B20463CD7C3');
        $this->addSql('ALTER TABLE pointage DROP CONSTRAINT FK_7591B20ED5CA9E6');
        $this->addSql('ALTER TABLE pointage DROP CONSTRAINT FK_7591B20A0905086');
        $this->addSql('ALTER TABLE pointage DROP CONSTRAINT FK_7591B20A76ED395');
        $this->addSql('ALTER TABLE pointage DROP CONSTRAINT FK_7591B201C6ED750');
        $this->addSql('ALTER TABLE pointage_pause DROP CONSTRAINT FK_FE748B79E58DA11D');
        $this->addSql('ALTER TABLE poste DROP CONSTRAINT FK_7C890FABED5CA9E6');
        $this->addSql('ALTER TABLE poste DROP CONSTRAINT FK_7C890FAB9F2C3FAB');
        $this->addSql('ALTER TABLE poste DROP CONSTRAINT FK_7C890FABA76ED395');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD2463CD7C3');
        $this->addSql('ALTER TABLE service_manager DROP CONSTRAINT FK_35A07725ED5CA9E6');
        $this->addSql('ALTER TABLE service_manager DROP CONSTRAINT FK_35A07725A76ED395');
        $this->addSql('ALTER TABLE staff_competence DROP CONSTRAINT FK_728678AEA76ED395');
        $this->addSql('ALTER TABLE staff_competence DROP CONSTRAINT FK_728678AE15761DAB');
        $this->addSql('ALTER TABLE support_attachment DROP CONSTRAINT FK_5BEB1D99700047D2');
        $this->addSql('ALTER TABLE support_attachment DROP CONSTRAINT FK_5BEB1D998A0E4E7F');
        $this->addSql('ALTER TABLE support_attachment DROP CONSTRAINT FK_5BEB1D99A2B28FE8');
        $this->addSql('ALTER TABLE support_reply DROP CONSTRAINT FK_F12D038700047D2');
        $this->addSql('ALTER TABLE support_reply DROP CONSTRAINT FK_F12D03860BB6FE6');
        $this->addSql('ALTER TABLE support_ticket DROP CONSTRAINT FK_1F5A4D53463CD7C3');
        $this->addSql('ALTER TABLE support_ticket DROP CONSTRAINT FK_1F5A4D5360BB6FE6');
        $this->addSql('ALTER TABLE support_ticket DROP CONSTRAINT FK_1F5A4D53BB1B0F33');
        $this->addSql('ALTER TABLE tuto_read DROP CONSTRAINT FK_4D239655A76ED395');
        $this->addSql('ALTER TABLE tuto_read DROP CONSTRAINT FK_4D2396557CB6CDBB');
        $this->addSql('ALTER TABLE tutoriel DROP CONSTRAINT FK_A2073AED463CD7C3');
        $this->addSql('ALTER TABLE tutoriel DROP CONSTRAINT FK_A2073AED9F2C3FAB');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649463CD7C3');
        $this->addSql('ALTER TABLE validation_hebdo DROP CONSTRAINT FK_1C440497463CD7C3');
        $this->addSql('ALTER TABLE validation_hebdo DROP CONSTRAINT FK_1C440497A76ED395');
        $this->addSql('ALTER TABLE validation_hebdo DROP CONSTRAINT FK_1C4404976AF12ED9');
        $this->addSql('ALTER TABLE zone DROP CONSTRAINT FK_A0EBC007463CD7C3');
        $this->addSql('DROP TABLE absence');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE centre');
        $this->addSql('DROP TABLE centre_note');
        $this->addSql('DROP TABLE competence');
        $this->addSql('DROP TABLE completion');
        $this->addSql('DROP TABLE completion_haccp_proof');
        $this->addSql('DROP TABLE correction_pointage');
        $this->addSql('DROP TABLE event_log');
        $this->addSql('DROP TABLE haccp_equipement');
        $this->addSql('DROP TABLE incident');
        $this->addSql('DROP TABLE incident_staff');
        $this->addSql('DROP TABLE "lead"');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE mission');
        $this->addSql('DROP TABLE mission_categorie');
        $this->addSql('DROP TABLE mission_haccp_spec');
        $this->addSql('DROP TABLE planning_snapshot');
        $this->addSql('DROP TABLE planning_template');
        $this->addSql('DROP TABLE planning_template_absence');
        $this->addSql('DROP TABLE planning_template_shift');
        $this->addSql('DROP TABLE planning_week');
        $this->addSql('DROP TABLE pointage');
        $this->addSql('DROP TABLE pointage_pause');
        $this->addSql('DROP TABLE poste');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_manager');
        $this->addSql('DROP TABLE staff_competence');
        $this->addSql('DROP TABLE support_attachment');
        $this->addSql('DROP TABLE support_reply');
        $this->addSql('DROP TABLE support_ticket');
        $this->addSql('DROP TABLE tuto_read');
        $this->addSql('DROP TABLE tutoriel');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE validation_hebdo');
        $this->addSql('DROP TABLE zone');
    }
}
