<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Prestation — offre commerciale publique d'un centre (module Web/Site, Branche 1).
 * Rattachée au centre (tenant), supprimée en cascade avec lui. PostgreSQL.
 */
final class Version20260630014002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Prestation (centre_id) — contenu public minimal du site client, isolé par tenant (PostgreSQL).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE prestation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, ordre INT DEFAULT 0 NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, centre_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_prestation_centre ON prestation (centre_id)');
        $this->addSql('ALTER TABLE prestation ADD CONSTRAINT FK_51C88FAD463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE prestation DROP CONSTRAINT FK_51C88FAD463CD7C3');
        $this->addSql('DROP TABLE prestation');
    }
}
