<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701024116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Console agence : Centre.abonnement_mensuel_cents (MRR) + plateforme_ia_quota (budget IA super-admin).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE plateforme_ia_quota (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, periode VARCHAR(7) NOT NULL, appels INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_plateforme_ia_quota_periode ON plateforme_ia_quota (periode)');
        $this->addSql('ALTER TABLE centre ADD abonnement_mensuel_cents INT DEFAULT 0 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE plateforme_ia_quota');
        $this->addSql('ALTER TABLE centre DROP abonnement_mensuel_cents');
    }
}
