<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618012542 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE planning_note (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              date DATE NOT NULL,
              contenu VARCHAR(280) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              created_by INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_76BF25A463CD7C3 ON planning_note (centre_id)');
        $this->addSql('CREATE INDEX IDX_76BF25ADE12AB56 ON planning_note (created_by)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_note
            ADD
              CONSTRAINT FK_76BF25A463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              planning_note
            ADD
              CONSTRAINT FK_76BF25ADE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE planning_note DROP CONSTRAINT FK_76BF25A463CD7C3');
        $this->addSql('ALTER TABLE planning_note DROP CONSTRAINT FK_76BF25ADE12AB56');
        $this->addSql('DROP TABLE planning_note');
    }
}
