<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702041023 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Plan : catalogue de packs agence + rattachement Centre->Plan.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, cle VARCHAR(60) NOT NULL, prix_mensuel_cents INT DEFAULT 0 NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DD5A5B7D41401D17 ON plan (cle)');
        $this->addSql('ALTER TABLE centre ADD plan_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE centre ADD CONSTRAINT FK_C6A0EA75E899029B FOREIGN KEY (plan_id) REFERENCES plan (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C6A0EA75E899029B ON centre (plan_id)');
    }

    public function down(Schema $schema): void
    {
        // Retirer d'abord la FK/colonne du centre, puis la table plan (ordre des dépendances).
        $this->addSql('ALTER TABLE centre DROP CONSTRAINT FK_C6A0EA75E899029B');
        $this->addSql('DROP INDEX IDX_C6A0EA75E899029B');
        $this->addSql('ALTER TABLE centre DROP plan_id');
        $this->addSql('DROP TABLE plan');
    }
}
