<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701015114 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CRM : contact (PII chiffrees, dedup centre+email_hash) + avis + relance.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE avis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note INT NOT NULL, commentaire TEXT DEFAULT NULL, reponse TEXT DEFAULT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, centre_id INT NOT NULL, contact_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F91ABF0E7A1254A ON avis (contact_id)');
        $this->addSql('CREATE INDEX idx_avis_centre ON avis (centre_id)');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom TEXT NOT NULL, email TEXT NOT NULL, telephone TEXT DEFAULT NULL, email_hash VARCHAR(64) NOT NULL, segments JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, centre_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_contact_centre ON contact (centre_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_contact_centre_email ON contact (centre_id, email_hash)');
        $this->addSql('CREATE TABLE relance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, motif VARCHAR(20) NOT NULL, texte TEXT DEFAULT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, centre_id INT NOT NULL, contact_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50BBC126E7A1254A ON relance (contact_id)');
        $this->addSql('CREATE INDEX idx_relance_centre ON relance (centre_id)');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relance ADD CONSTRAINT FK_50BBC126463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relance ADD CONSTRAINT FK_50BBC126E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF0463CD7C3');
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF0E7A1254A');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E638463CD7C3');
        $this->addSql('ALTER TABLE relance DROP CONSTRAINT FK_50BBC126463CD7C3');
        $this->addSql('ALTER TABLE relance DROP CONSTRAINT FK_50BBC126E7A1254A');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE relance');
    }
}
