<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701012216 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'B2B : demande_b2b (demandes par centre) + devis (brouillon IA, lignes JSON, total centimes).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE demande_b2b (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_contact VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL, telephone VARCHAR(30) NOT NULL, societe VARCHAR(180) DEFAULT NULL, type_evenement VARCHAR(120) NOT NULL, nb_personnes INT DEFAULT NULL, date_souhaitee DATE DEFAULT NULL, message TEXT NOT NULL, statut VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, centre_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_demande_b2b_centre ON demande_b2b (centre_id)');
        $this->addSql('CREATE TABLE devis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lignes JSON NOT NULL, total_cents INT NOT NULL, statut VARCHAR(30) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, centre_id INT NOT NULL, demande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B27C52B80E95E18 ON devis (demande_id)');
        $this->addSql('CREATE INDEX idx_devis_centre ON devis (centre_id)');
        $this->addSql('ALTER TABLE demande_b2b ADD CONSTRAINT FK_82E68BC2463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52B463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52B80E95E18 FOREIGN KEY (demande_id) REFERENCES demande_b2b (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE demande_b2b DROP CONSTRAINT FK_82E68BC2463CD7C3');
        $this->addSql('ALTER TABLE devis DROP CONSTRAINT FK_8B27C52B463CD7C3');
        $this->addSql('ALTER TABLE devis DROP CONSTRAINT FK_8B27C52B80E95E18');
        $this->addSql('DROP TABLE demande_b2b');
        $this->addSql('DROP TABLE devis');
    }
}
