<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618013444 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Historique des contrats (E3) + backfill d\'un contrat actif par employé.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE contrat (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type_contrat VARCHAR(30) NOT NULL,
              date_debut DATE NOT NULL,
              date_fin DATE DEFAULT NULL,
              qualification VARCHAR(120) DEFAULT NULL,
              heures_hebdo INT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              centre_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_60349993463CD7C3 ON contrat (centre_id)');
        $this->addSql('CREATE INDEX IDX_60349993A76ED395 ON contrat (user_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              contrat
            ADD
              CONSTRAINT FK_60349993463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              contrat
            ADD
              CONSTRAINT FK_60349993A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        // Backfill : un contrat actif (date_fin NULL) par employé ayant déjà des
        // infos contrat sur sa fiche User. date_debut = date_embauche (ou aujourd'hui
        // si absente), qualification = emploi, heures_hebdo = heures_hebdo.
        $this->addSql(<<<'SQL'
            INSERT INTO contrat (type_contrat, date_debut, date_fin, qualification, heures_hebdo, created_at, centre_id, user_id)
            SELECT
              COALESCE(u.type_contrat, 'CDI'),
              COALESCE(u.date_embauche, CURRENT_DATE),
              NULL,
              u.emploi,
              u.heures_hebdo,
              NOW(),
              u.centre_id,
              u.id
            FROM "user" u
            WHERE u.centre_id IS NOT NULL
              AND (u.type_contrat IS NOT NULL OR u.date_embauche IS NOT NULL)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contrat DROP CONSTRAINT FK_60349993463CD7C3');
        $this->addSql('ALTER TABLE contrat DROP CONSTRAINT FK_60349993A76ED395');
        $this->addSql('DROP TABLE contrat');
    }
}
